# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='timestamp',
            new_name='Created Time',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='updated',
            new_name='Updated Time',
        ),
    ]
