# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160630_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Created Time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Updated Time',
            new_name='updated',
        ),
    ]
