# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
